FROM alpine:3.7
RUN apk add --no-cache git bash

FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY elk-gke.pem ./
COPY ca.cert ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
